FROM gcr.io/distroless/cc-debian12:nonroot

ARG TARGET=x86_64-unknown-linux-gnu

WORKDIR /app

COPY target/${TARGET}/release/bgm-backend /app/bgm-backend

ENTRYPOINT ["/app/bgm-backend"]
CMD ["--help"]
