inputs:
  node-version:
    description: 'node version'
    required: false
    default: '^22.11.0'

name: 'Setup Node and run npm ci'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        node-version: '${{ inputs.node-version }}'
        package-manager-cache: false

    - run: |
        npm i -g corepack
        corepack enable
        corepack prepare --activate
        pnpm --version
      shell: bash
      name: install pnpm

    - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: ~/.local/share/pnpm/store/
        key: ${{ runner.os }}-1-node${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-1-node${{ inputs.node-version }}-

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
