inputs:
  node-version:
    description: 'node version'
    required: false
    default: '^22.11.0'

name: 'Setup Node and run npm ci'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4
      with:
        node-version: '${{ inputs.node-version }}'

    - run: |
        npm i -g corepack
        corepack enable
        corepack prepare --activate
        pnpm --version
      shell: bash
      name: install pnpm

    - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4
      with:
        path: ~/.local/share/pnpm/store/
        key: ${{ runner.os }}-1-node${{ inputs.node-version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-1-node${{ inputs.node-version }}-

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
