inputs:
  node-version:
    description: 'node version'
    required: false
    default: '18.x'

name: 'Setup Node and run npm ci'
description: 'setup node env'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '${{ inputs.node-version }}'

    - run: |
        corepack enable
        corepack prepare --activate
        pnpm --version
      shell: bash
      name: install pnpm

    - name: Get nodejs version
      shell: bash
      id: nodejs-version
      run: echo "version=$(node -e 'console.log(process.version)')" >> $GITHUB_OUTPUT

    - uses: actions/cache@v3
      with:
        path: ~/.local/share/pnpm/store/
        key: ${{ runner.os }}-1-node${{ steps.nodejs-version.outputs.version }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-1-node${{ steps.nodejs-version.outputs.version }}-

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
