name: 'Setup Node and run npm ci'
description: 'run actions/setup-node and `npm ci`'
runs:
  using: 'composite'
  steps:
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn --immutable
      shell: bash
