name: Release(GitHub)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn

      - run: node .github/scripts/changelog.js | tee changelog.md

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Upload GitHub Release
        run: gh release create "$TAG" --title "$TAG" -F changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
