name: Release(openapi)

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: yarn

      - run: yarn
      - run: yarn run-file ./scripts/export-openapi.ts

      - uses: actions/checkout@v3
        with:
          repository: 'bangumi/dev-docs'
          path: dev-docs

      - run: cp ./dist/private.yaml ./dev-docs/api.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          path: dev-docs
          token: ${{ secrets.PAT }}
          title: Update Private Openapi Specification from bangumi/server-private
          push-to-fork: bangumi-bot/dev-docs
          branch: 'update-upstream-graphql'
          author: 'bangumi-bot <124712095+bangumi-bot@users.noreply.github.com>'
          committer: 'bangumi-bot <124712095+bangumi-bot@users.noreply.github.com>'
