name: Release(GitHub)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up git-cliff
        uses: kenji-miyake/setup-git-cliff@2778609c643a39a2576c4bae2e493b855eb4aee8 # v2

      - run: git cliff --current -o changelog.md

      - name: Upload GitHub Release
        run: gh release create "${GITHUB_REF}" -F changelog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
