name: Release(GitHub)

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  github:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        uses: trim21/action-changelog@includeTypes
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
          writeToFile: false
          includeTypes: feat,fix,revert

      - name: Upload GitHub Release
        run: gh release create "${GITHUB_REF}" --notes "${CHANGELOG}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG: '${{ steps.changelog.outputs.changes }}'
