name: 'Run TODO to Issue'

on:
  push:
    branches:
      - 'master'
jobs:
  build:
    runs-on: 'ubuntu-24.04'
    steps:
      - uses: 'actions/checkout@v5'
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v5'
